# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vector_clock_pb2 as vector__clock__pb2


class VectorClockServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateVectorClock = channel.unary_unary(
                '/vectorclock.VectorClockService/UpdateVectorClock',
                request_serializer=vector__clock__pb2.VectorClockRequest.SerializeToString,
                response_deserializer=vector__clock__pb2.VectorClockReply.FromString,
                )


class VectorClockServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateVectorClock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorClockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateVectorClock': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVectorClock,
                    request_deserializer=vector__clock__pb2.VectorClockRequest.FromString,
                    response_serializer=vector__clock__pb2.VectorClockReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vectorclock.VectorClockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VectorClockService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateVectorClock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vectorclock.VectorClockService/UpdateVectorClock',
            vector__clock__pb2.VectorClockRequest.SerializeToString,
            vector__clock__pb2.VectorClockReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
