# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vector_clock.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12vector_clock.proto\x12\x0bvectorclock\"\x8f\x01\n\x12VectorClockRequest\x12\x45\n\x0bvectorClock\x18\x01 \x03(\x0b\x32\x30.vectorclock.VectorClockRequest.VectorClockEntry\x1a\x32\n\x10VectorClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\xb9\x01\n\x10VectorClockReply\x12\x17\n\x0f\x61\x63knowledgement\x18\x01 \x01(\t\x12Q\n\x12updatedVectorClock\x18\x02 \x03(\x0b\x32\x35.vectorclock.VectorClockReply.UpdatedVectorClockEntry\x1a\x39\n\x17UpdatedVectorClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32k\n\x12VectorClockService\x12U\n\x11UpdateVectorClock\x12\x1f.vectorclock.VectorClockRequest\x1a\x1d.vectorclock.VectorClockReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_clock_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VECTORCLOCKREQUEST_VECTORCLOCKENTRY']._options = None
  _globals['_VECTORCLOCKREQUEST_VECTORCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_VECTORCLOCKREPLY_UPDATEDVECTORCLOCKENTRY']._options = None
  _globals['_VECTORCLOCKREPLY_UPDATEDVECTORCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_VECTORCLOCKREQUEST']._serialized_start=36
  _globals['_VECTORCLOCKREQUEST']._serialized_end=179
  _globals['_VECTORCLOCKREQUEST_VECTORCLOCKENTRY']._serialized_start=129
  _globals['_VECTORCLOCKREQUEST_VECTORCLOCKENTRY']._serialized_end=179
  _globals['_VECTORCLOCKREPLY']._serialized_start=182
  _globals['_VECTORCLOCKREPLY']._serialized_end=367
  _globals['_VECTORCLOCKREPLY_UPDATEDVECTORCLOCKENTRY']._serialized_start=310
  _globals['_VECTORCLOCKREPLY_UPDATEDVECTORCLOCKENTRY']._serialized_end=367
  _globals['_VECTORCLOCKSERVICE']._serialized_start=369
  _globals['_VECTORCLOCKSERVICE']._serialized_end=476
# @@protoc_insertion_point(module_scope)
