# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_sync.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftime_sync.proto\x12\x08timesync\"\x07\n\x05\x45mpty\"*\n\x15RegisterClientRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\";\n\x12\x43lientTimeResponse\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\x14\n\x0cmilliseconds\x18\x02 \x01(\x05\"$\n\x0eTimeAdjustment\x12\x12\n\nadjustment\x18\x01 \x01(\x03\"3\n\nTimeUpdate\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\x14\n\x0cmilliseconds\x18\x02 \x01(\x05\x32\x96\x02\n\x0fTimeSyncService\x12\x42\n\x0eRegisterClient\x12\x1f.timesync.RegisterClientRequest\x1a\x0f.timesync.Empty\x12\x42\n\x11RequestClientTime\x12\x0f.timesync.Empty\x1a\x1c.timesync.ClientTimeResponse\x12=\n\x10\x41\x64justClientTime\x12\x18.timesync.TimeAdjustment\x1a\x0f.timesync.Empty\x12<\n\x11StreamTimeUpdates\x12\x0f.timesync.Empty\x1a\x14.timesync.TimeUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'time_sync_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=29
  _globals['_EMPTY']._serialized_end=36
  _globals['_REGISTERCLIENTREQUEST']._serialized_start=38
  _globals['_REGISTERCLIENTREQUEST']._serialized_end=80
  _globals['_CLIENTTIMERESPONSE']._serialized_start=82
  _globals['_CLIENTTIMERESPONSE']._serialized_end=141
  _globals['_TIMEADJUSTMENT']._serialized_start=143
  _globals['_TIMEADJUSTMENT']._serialized_end=179
  _globals['_TIMEUPDATE']._serialized_start=181
  _globals['_TIMEUPDATE']._serialized_end=232
  _globals['_TIMESYNCSERVICE']._serialized_start=235
  _globals['_TIMESYNCSERVICE']._serialized_end=513
# @@protoc_insertion_point(module_scope)
